spring.datasource.url=jdbc:mysql://localhost:3306/springboot_db
spring.datasource.username=root
spring.datasource.password=chuong1507@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.application.name=SpringBoot_2
server.port=8081

jwt.secret=QXruiMenxfoFGnhIZoufgwfMPFSm2ZOfwDa81ngMka/o2FmmOplVmUZM8pJ7qi89b7NpANdPd6Z+Iswq+zekxg==


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile